CREATE TABLE Users (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE Game (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    release_date DATE NOT NULL,
    rating FLOAT NOT NULL,
    cost INT NOT NULL,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE Game_Ref (
    user_id INT NOT NULL REFERENCES Users (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    game_id INT NOT NULL REFERENCES Game (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Accounts (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    amount INT DEFAULT 0,
    type ENUM ('Visa', 'Mastercard') NOT NULL DEFAULT 'Visa',
    user_id INT NOT NULL REFERENCES Users (id)
);